var sentence_arr =  [ 
[ // 0 - 1st grade
"I am Joe.",
"My dog is Spot.",
"Spot runs.",
"Spot jumps.",
"I see Spot.",
"I see Spot jump.",
"I run with Spot.",
"I have a cat.",
"My cat is Fluff.",
"Fluff plays.",
"Fluff jumps.",
"Fluff eats.",
"Spot eats.",
"I have a friend.",
"My friend is Sam.",
"Sam likes Spot.",
"Sam likes Fluff.",
"Sam sees Spot.",
"Sam sees Fluff.",
"Look, Sam",
"I say.",
"Look at Fluff.",
"Look at Spot.",
"Let's go, Sam",
"I say.",
"Let's go, Spot.",
"I say.",
"Let's go, Fluff.",
"I say.",
"We go out."
],
[ // 1 - 2nd grade
"Today I am on vacation.",
"My vacation is at the beach.",
"I like seeing the beach.",
"I like feeling the sun.",
"I like the yellow sand.",
"I like the ocean spray.",
"Today it is very sunny.",
"I put on sun screen.",
"Then I got my surfboard.",
"I like to ride a surfboard.",
"The waves are very big.",
"The waves move very fast.",
"Surfing is very fun.",
"I am tired from surfing.",
"I lie down on a towel.",
"I am enjoying my vacation.",
"Later I will meet friends.",
"Now I am hungry.",
"I go to the burger stand.",
"I order a double cheeseburger.",
"I also have some fries.",
"I drink a big milkshake.",
"After lunch I am sleepy.",
"I take a nap in my hotel.",
"After dinner, I will meet my friends.",
"We will go to a movie.",
"I like action movies.",
"James Bond is my favorite.",
"I like Iron Man too.",
"Tonight's movie is about spies."
],
[ // 2 - 3rd grade
"Today I went to visit New York City.",
"I wanted to see all the sights there.",
"My flight landed at JFK airport in Queens.",
"Then I took a taxi to my hotel in Manhattan.",
"I checked in and went to my room.",
"After unpacking, I went outside.",
"This part of Manhattan is called Greenwich Village.",
"I saw a place where they sold pizza.",
"I went inside and had some.",
"Then I walked to Washington Square Park.",
"It is a very old park, more than 150 years old.",
"One corner of the park has built in chess tables.",
"Each table is made of concrete.",
"The board is part of the table top.",
"People bring their own pieces and play outdoors. ",
"The middle of the park has a fountain.",
"Near the fountain is the famous Arch.",
"The Arch was built in 1892.",
"It has statues of George Washington on it.",
"Lots of people come to the park.",
"It is a fun place to visit.",
"Another part of New York City is Central Park.",
"Central Park is a very big place.",
"It has lots of green trees and paths.",
"It has two skating rinks and a zoo.",
"It has a theatre and a Great Lawn.",
"Once it had small villages where poor people lived.",
"They all had to leave when the park was built.",
"I visited the Central Park Zoo and saw seals.",
"I also saw polar bears and many reptiles."
],
[ // 3 - 4th grade
"Today, television is found in most homes.",
"It is also found in many places that are not homes.",
"It is found in the workplace and waiting rooms.",
"It is found in food service places and churches.",
"We use TV for many reasons.",
"Some reasons are to have fun and to learn things.",
"Other reasons are getting news and facts access.",
"Since TV started in 1925, many people have never known a world without it.",
"Many people do not know that TV is less than 100 years old.",
"TV has two main functions.",
"The first is to observe real time events.",
"This is done for home and business safety.",
"The second is to provide programs for large numbers of people.",
"The safety function of TV is most often done with closed circuit TV.",
"This type of TV has a direct, wired connection from the camera to the set.",
"Only the sets connected to the camera can show the image.",
"Using this type makes it easier for places to be observed.",
"Fewer people are needed.",
"This was one of the first uses of TV in the Soviet Union.",
"TV is called a mass medium.",
"This means that programs can be given to a large group.",
"There are many kinds of TV shows.",
"They are listed below.",
"The news show presents recent events.",
"The events can be of a local or national nature.",
"Sometimes news from other countries is presented.",
"This helps viewers know about things going on in the world.",
"Sports shows present athletes in real time or recorded form.",
"These events come with spoken comments from sports experts.",
"The comments tell viewers what is happening on screen.",
"It tells them what it means for the players.",
],
[ // 4 - 5th grade
"Mary wanted to buy a new hat to wear in church on Sunday.",
"She went to the hat store to look at their hats.",
"Mary looked at all the hats in the hat store and at last she found a good one.",
"Mary asked the price of the hat she had found.",
"When they told her the price Mary thought it was too much.",
"Even so, Mary wanted the hat very much and thought she could afford it.",
"Mary told them that she would buy the hat.",
"Mary was very happy that she had a new hat.",
"Mary said she would wear her new hat to church the very next Sunday to show her friends.",
"Mary went to church wearing her new hat and all her friends saw her.",
"Mary’s friend, Alice, told Mary that she liked her new hat very much.",
"Mary’s other friend, Nancy, said that the new hat was awesome and cool.",
"Mary wondered if her friend John would like her new hat that much.",
"John didn’t seem to notice Mary’s new hat that day which made Mary sad.",
"Mary went home and put her new hat in a hatbox on a high shelf in the closet.",
"Mary liked to play the fiddle while her new friend Helga, played the banjo.",
"Mary thought that fiddle and banjo sounded nice when played at the same time.",
"Mary and Helga played a song called “Under the Double Eagle” that they had practiced.",
"Mary thought their song sounded good enough to play for her friend John.",
"Mary invited John to her house to hear her play her song with Helga.",
"John said he really liked the song that they played because it was so happy sounding.",
"John decided to record them playing their song on his smart phone.",
"John asked them if he could upload the video to YouTube because it was so cool.",
"Mary and Helga agreed to be on YouTube with their song and it got lots of hits.",
"Soon Mary and Helga’s video went viral and they were asked to go on \“The X Factor.\”",
"Mary and Helga won on “The X Factor” and became instant music stars.",
"Mary and Helga went on a concert tour of Europe.",
"When they were in Paris they saw the Eiffel Tower.",
"When they were in London they saw Big Ben.",
"When they went home they told all their friends about their tour."
],
[ // 5 - 6th grade
"Today I wanted to take a walk in the park because it was very sunny.",
"When I got to the park I saw that it was a cool windy day.",
"As I walked through the park I looked at all the trees with their leaves.",
"I also looked at the blue and yellow flowers that were growing in the grass.",
"The first person that I met was an old man with a black wooden cane.",
"We nodded to each other and then each went on our own way without speaking.",
"I sat on a park bench and looked at the blue sky and drifting clouds.",
"As I sat, I thought of my old friend, George, who I used to know.",
"Just then, George walked up to the park bench and sat down next to me.",
"I was very surprised to see my friend George just when I thought of him.",
"\"Hello, old friend,\" I said to him, \"it is very nice to see you today.\"",
"\"I’m glad to see you and I hope you are well,\" said George to me.",
"\"I am well,\" I said, \"because it is a sunny day in this nice park.\"",
"\"Yes, it is,\" said George, \"and I am happy to be here on this day.\"",
"Then I asked my friend, \"Why are you happy to be here on this day?\"",
"\"I am happy because it is a sunny day in this nice park,\" he said.",
"\"That’s right, George,\" I said to him, \"any day as sunny as this is special.\"",
"\"This is my first visit to this park,|' said George to me after a silence.",
"\"I visit this park all the time,\" I said to George, \"it’s a good one.\"",
"\"I agree with you,\" said George quickly, \"that it is a fine place to visit.\"",
"\"Did you know,\" I asked my friend, \"that this park is named after George Washington?\"",
"\"I think I knew that once,\" George replied, \"but I forgot it somehow or other.\"",
"\"This is one of the oldest parks in America,\" I said, \"did you know that?\".",
"\"Can you tell me what year the park was first opened for all to enjoy?\"",
"Washington Square Park was created around 1849, but it was not the same as now.\"",
"I explained that the park was given a new design in 1871 with new pathways.",
"\"Well, it is a fine place to be on a sunny day,\" said George gently.",
"\"I then said goodbye to my friend George because I had to go to work.\"",
"\"Give my regards to your wife; let’s all meet for lunch sometime soon,\" said George.",
"\"I would really like that and so would Marie, I am sure,\" I told him."
],
[ // 6 - 7th grade
"Once there was a man who married, for his second wife, the most haughty woman you ever saw.",
"She had, by a former husband, two daughters of her own, who were like her in all things.",
"He had by his first wife, a young pretty daughter, who was good and sweet like her mother.",
"No sooner was the wedding over but the new wife began to show herself in her true colors.",
"She could not bear the goodness of this pretty girl, because it made her own daughters look bad.",
"She made her do all the hardest housework, washing dishes and cleaning all the rooms of their home.",
"The young girl slept in the attic, on a straw bed, while her sisters slept in nice rooms.",
"The poor girl bore it all patiently, and dared not tell her father, for his wife bossed him.",
"When she had done her work, she used to go to the fireplace, and sit in the ashes.",
"Because of this, her sisters called her the name Cinderella to shame her for the way she looked.",
"Cinderella, although dressed poorly, was much more good looking than her sisters, who dressed in very fine fashion.",
"When the king's son gave a ball, he invited all young persons of fashion to come to it.",
"Our young misses were also going, for they cut a very grand figure among those of high fashion.",
"They were happy they were going, and busy in choosing the gowns and hair styles they liked best.",
"This was hard for Cinderella, because she ironed her sister's dresses, pleated their ruffles and shined their shoes.",
"Cinderella's sisters talked all day long of nothing but how they should be dressed and their good looks.",
"\"For my outfit,\" said the eldest, \"I will wear my fine red velvet dress with fancy gold beads.\"",
"\"And I,\" said the youngest, \"will wear a silver gown with purple highlights and a pink feather wrap.\"",
"They sent for the best hair stylist to adjust their hairdos, and they made sure they looked stunning.",
"They also talked with Cinderella about this, for she had great ideas, and her advice was always good.",
" She even offered to fix their hair, which they very were happy to have her do for them.",
"As she was doing this, they said to her, \"Cinderella, would you like to go to the ball?\"",
"\"Oh!\" she said, \"you only tease me, for someone like me could not go to such a place.\"",
"\"Yes,\" they replied, \"for people would laugh to see a Cinderella at a fancy ball like this one.\"",
"Anyone but Cinderella would have ruined their hairdos, but she was very good, and fixed them very well.",
"The day came when they went to court, and Cinderella watched them go as long as she could.",
"When she lost sight of them, she started to cry and cry as though her heart would break.",
"Her Fairy Godmother, who saw her all in tears, asked her what in the world was the matter.",
"\"I wish I could.I wish I could,\" was all Cinderella could manage to say through her tears.",
"Her Fairy Godmother said to her, \"You wish you could go to the ball; is it not so?\"",
"\"Yes,\" cried Cinderella, with a great sigh, wiping the tears from her eyes and face with her hands.",
"\"Well,\" said her Godmother, \"be a good girl, and I will make it happen that you shall go.\"",
"Then she took her into her room, and said to her, \"Run into the garden, and bring me a pumpkin.\"",
"Cinderella quickly went to gather the finest pumpkin she could get, and brought it to her Fairy Godmother.",
"Cinderella had no idea at all how this large orange pumpkin could help her go to the ball.",
"Her Fairy Godmother soon scooped out all of the inside of the pumpkin, leaving nothing but the rind.",
"Having done this, she struck the pumpkin with her wand, and it was turned into a fine coach.",
"She then looked into her mousetrap, found six mice, all alive, and ordered Cinderella to open the trapdoor.",
"She gave each mouse a little tap with her wand, and the mouse turned into a fine horse.",
"This made them into a very fine set of six horses of a pretty mouse colored dapple gray.",
"Cinderella said, \"If there is a rat in the rat trap we can turn him into a coachman.\"",
"\"You are quite right,\" replied her Fairy Godmother, \"Go and look to see what you can find there.\"",
"Cinderella brought the rat trap to her, and saw that in it there were three huge gray rats.",
"The Fairy Godmother chose the largest one, touched him with her wand, and turned him into a coachman.",
"After that, she said to her, \"Go once more into the garden, and you will find six lizards.\"",
"She brought them to her Godmother who turned them into six footmen, who ran along behind the coach.",
"The Fairy Godmother then said to Cinderella, \"Well, are you not pleased with your coach, horses and servants?\"",
"\"Oh, yes indeed I am,\" she cried; \"but must I go to the ball in these nasty rags?\"",
"Her Godmother then touched her with her wand, and her clothes turned into cloth of gold and silver.",
"This done, she gave her a pair of glass slippers that glittered and fit her feet just so.",
"Cinderella got up into her coach but her Fairy Godmother told her not to stay out past midnight.",
"She said that if she stayed one moment past midnight, the coach would be a plain pumpkin again.",
"She said the horses would be mice, her coachman a rat, her footmen lizards, and her clothes rags.",
"She promised her Godmother to leave the ball before midnight and drove away, happy and full of joy.",
" The prince, who was told that a princess whom no one knew had arrived, ran to receive her.",
"He gave her his hand as she got out of the coach, and led her into the hall.",
"There was silence as they all stopped dancing and the violins ceased to play, because of Cinderella's beauty.",
"The king himself was watching her, telling the queen that he had never seen so lovely a girl.",
"The king's son led her to the best seat, and then took her out to dance with him.",
"She danced with so much grace, charm and style that all the people more and more admisentence_arrred her.",
"A fine meal was served, but the prince ate nothing, so busy was he in gazing on her.",
"While Cinderella was charming them all, she saw it was close to midnight, so she left quickly.",
"When she got home, she ran to seek out her Fairy Godmother and thanked her for her help.",
"She said she wished she could go to the ball again, because the king's son had invited her.",
"As she was telling her Godmother what happened at the ball, her two sisters knocked at the door.",
"\"You stayed a long time!\" she cried, rubbing her eyes and stretching as if she had been sleeping.",
"\"Had you been at the ball,\" said one of her sisters, \"you would not have tired of it.\"",
"The finest princess came to the ball who was the most lovely that mortal eyes have ever seen.",
"Cinderella asked them the name of that princess; but they told her that they did not know it.",
"They said the king's son loved her and would give all the world to know who she was.",
"At this Cinderella replied, \"She must be very fine indeed. How happy you have been to see her.\"" ,
"The next day the sisters were at the ball, and so was Cinderella, dressed more richly than before.",
"The king's son was always near her, and never ceased his loving praises and kind speeches to her.",
"All this was so pleasant to her, and, indeed, she quite forgot what her Godmother had told her.",
"She thought that it was no later than ten o'clock when she counted the clock striking twelve midnight.",
"She jumped up and fled like the wind, with the prince running after her, trying to catch her.",
" She left behind one of her glass slippers, which the prince picked up with the greatest of care.",
"She arrived home in her nasty old clothes, having nothing left but one of the little glass slippers.",
"The guards at the palace gate were asked if they had not seen a fine princess go out.",
"They replied that they had seen no one leave but a young girl, not dressed like a princess.",
"When the two sisters returned from the ball Cinderella asked them if the fine lady had been there.",
"They told her, yes, but that she hurried off as soon as it struck twelve and vanished away.",
"They said she left in so much haste that she dropped one of her pretty little glass slippers.",
"They said that the prince had picked it up and that he was in love with its owner.",
"The next day, the prince proclaimed that he would marry her whose foot this slipper would just fit.",
"They began to try it on the princesses, then the duchesses and all the court, but in vain.",
"It was brought to the two sisters, who tried to force their foot into the slipper without success.",
"Cinderella, who knew that it was her slipper, asked them, \"Let me see if it will fit me.\"",
"Her sisters burst out laughing, and began to tease her, saying that she could not be the princess.",
"The duke who was sent with the slipper said that he had orders to let all try it.",
"He had Cinderella sit down, and, putting the slipper to her foot, he found that it fit her.",
"Her two sisters were amazed, but then even more so, when Cinderella pulled out the other glass slipper.",
"In came her Fairy Godmother who touched her wand to Cinderella's clothes, which were changed into rich garments.",
"Now her two sisters found her to be that fine lady whom they had seen at the ball.",
"They threw themselves at her feet to beg pardon for all the ill treatment they had given her.",
"Cinderella took them up, and, as she embraced them, said that she forgave them with all her heart.",
"She was taken to the young prince right away, who thought she was even more charming than before.",
"A few days later, the prince and lovely Cinderella were married with great joy in the royal palace."
],
]
